function v = projectVersion()
%PROJECTVERSION Retorna a versão do projeto
v = struct( ...
    'name', 'MyProject', ...
    'version', '1.2.0', ...
    'date', '2025-01-15', ...
    'author', 'Léo Ribeiro' ...
);
end